version: '3.5'

services:
  db:
    container_name: mysql-database
    image: mysql:8.0.28-oracle	
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
  